version: "3.9"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: myappdb
    ports:
      - "3307:3306"
    volumes:
      - mydbdata:/var/lib/mysql
    networks:
      - appnet

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: myappdb
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - appnet

volumes:
  mydbdata:

networks:
  appnet:
