name: CI/CD for Flask App

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        run: docker build -t myflaskapp:latest .

      - name: Run App with Compose
        run: docker compose up -d

      - name: Health Check App
        run: |
          sleep 15
          curl --fail http://localhost:5000 || exit 1

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push to DockerHub
        run: |
          docker tag myflaskapp:latest mydockerhubuser/myflaskapp:latest
          docker push mydockerhubuser/myflaskapp:latest
